mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('report_it.urls', namespace='report_it')),
)

mysite/report_it/urls.py
from django.conf.urls import url
from report_it import views

urlpatterns = [
    url(r'^log/$', views.log, name='log'),
    url(r'^log/confirmation/$', views.confirmation, name='confirmation'),
    url(r'^$', views.index, name='index'),
] 

mysite/report_it/models.py
from django.db import models

# Create your models here.

mysite/report_it/forms.py
from django import forms

class IncidentLog(forms.Form):
    your_email = forms.EmailField(widget=forms.EmailInput(attrs={'type': 'email', 'placeholder': 'ex. userid@gmail.com'}), label='Your email*')
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Who were the people involved?'}), label='Name(s)', max_length=100, required=False)
    location = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Where did the incident occur?'}), label='Location', max_length=100, required=False)
    context = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Provide some details/descriptors of the incident.', 'id': 'context', 'class': 'pure-input-1-2'}), label='Context/Situation')
    quote = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Was something specific said?'}), label='Quote')
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'ex. #sexual harrassment, #bullying'}), label='Tags', max_length=50, required=False)

mysite/report_it/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings

from .forms import IncidentLog

def index(request):
    return render(request, 'report_it/index.html')

def log(request):
    if request.method == 'GET':
        form = IncidentLog(label_suffix='')
    else:
        form = IncidentLog(request.POST)
        if form.is_valid():
            email = form.cleaned_data['your_email']
            message = "Name(s): " + form.cleaned_data['name'] + "\n" + "Location: " + form.cleaned_data['location'] + "\n" + "Context/Situation: " + form.cleaned_data['context'] + "\n" + "Quote: " + form.cleaned_data['quote'] + "\n" + "Tags: " + form.cleaned_data['tags']
            try:
                send_mail('Incident Report', message, settings.EMAIL_HOST_USER, [email], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found. Please try again.')
            return HttpResponseRedirect('confirmation')
    return render(request, 'report_it/log.html', {'form': form})

def confirmation(request):
    return render(request, 'report_it/confirmation.html')

mysite/report_it/templates/report_it/confirmation.html
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

<style>
h1 {
    text-align: center;
}

h2 {
    margin-top: 50;
    text-align: center;
}

#log {
    display: table;
    margin: 0 auto;
}

</style>

<h2>Your incident log has been sent.</h2>
<h1>Thank you for using Report It!</h1>
<a id="log" class="pure-button pure-button-primary" href="{% url 'report_it:log' %}">Send Another Incident Report</a>

mysite/report_it/templates/report_it/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'report_it/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'report_it/buttons.css' %}" />

<header>
    <img class="welcome" src="http://tourdash.com/wp-content/uploads/2014/07/Start_With_Why.jpg">
    <h1 class="title">Welcome to Report It</h1>
</header>
<div class="description">
    <section class="what">
        <h1 class="subtitle">What Is Report It?</h1>
        <p>Report It provides an easy way to log incidents of bullying or sexual harassment.</p>
    </section>
    <section class="why">
        <h1 class="subtitle">Why Is This Important?</h1>
        <p>When certain incidents or situations make you feel uncomfortable, it can be difficult to recognize them as a pattern. Report It can help you track incidents to create a comprehensive report that demonstrates a pattern of bullying or sexual harassment.  This can be a starting point to make a solid case and take it further.</p>
    </section>
</div>
<a id="log" class="pure-button" href="{% url 'report_it:log' %}">Get Started</a>

mysite/report_it/templates/report_it/log.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'report_it/logStyle.css' %}" />
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

<h1 class="title">Report Details</h1>
<h2 class="subtitle">The information you provide here will generate an email for you to keep for your records.</h2>
<form method='post' class="pure-form pure-form-aligned">
    {% csrf_token %}
    <div class="pure-control-group">
        {{ form.as_p }}
    </div>
    <div class="wrapper">
        <input class="button" type="submit" value="Generate Email">
    </div>
</form>